{% set version = "1.2.1" %}

package:
  name: crystals
  version: {{ version }}

source:
  fn: crystals-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/crystals/crystals-{{ version }}.tar.gz
  sha256: b7f512c96505b250d2b0299b81b0a877f2474ca0a89f5562aaf37ffbd890f7ad

build:
  noarch: python
  number: 1
  entry_points:
    - crystals = crystals.__main__:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.6 # requires pathlib
    - pip
  run:
    - python >=3.6
    - numpy >=1.13, <2
    - spglib >=1.14, <2
    - pycifrw >=4.4.1, <5
    - requests >=2, <3

test:
  imports:
    - crystals
  commands:
    - python -m unittest discover --buffer

about:
  home: https://crystals.readthedocs.io
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Data structures for crystallography
  description: |
    crystals provides data structure to manipulate crystal structures, including parsing 
    crystal files, determining symmetries, and accessing atomic information.
  doc_url: https://crystals.readthedocs.io/
  dev_url: https://github.com/LaurentRDC/crystals

extra:
  recipe-maintainers:
    - LaurentRDC
