{% set version = "0.6.3" %}
{% set hash_type = "sha256" %}
{% set hash_value = "6acbae96a36a20107332cf1177d5aa8ebbc989ae3bd4d71cc8d46aff3df2dd7b" %}

package:
  name: 'crystals'
  version: '{{ version }}'

source:
  fn: 'crystals-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/c/crystals/crystals-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6 # requires pathlib
    - pip
  run:
    - python >=3.6
    - numpy >=1.13
    - spglib >=1.11
    - pycifrw >=4.4

test:
  imports:
    - crystals

about:
  home: https://crystals.readthedocs.io
  license: BSD 3-Clause
  license_family: BSD
  license_file: 'LICENSE'
  summary: Data structures for crystallography
  description: |
    crystals provides data structure to manipulate crystal structures, including parsing 
    crystal files, determining symmetries, and accessing atomic information.
  doc_url: 'https://crystals.readthedocs.io/'
  dev_url: 'https://github.com/LaurentRDC/crystals'

extra:
  recipe-maintainers: 
    - LaurentRDC
