{% set version = "0.6.7" %}
{% set hash_type = "sha256" %}
{% set hash_value = "3dcaa7e94633e0486cb2bb3bc0bbcfdcd359afbe61a38be5a38e8b241e27709e" %}

package:
  name: 'crystals'
  version: '{{ version }}'

source:
  fn: 'crystals-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/c/crystals/crystals-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6 # requires pathlib
    - pip
  run:
    - python >=3.6
    - numpy >=1.13, <2
    - spglib >=1.14, <2
    - pycifrw >=4.4.1, <5
    - requests >=2, <3

test:
  imports:
    - crystals

about:
  home: https://crystals.readthedocs.io
  license: BSD 3-Clause
  license_family: BSD
  license_file: 'LICENSE'
  summary: Data structures for crystallography
  description: |
    crystals provides data structure to manipulate crystal structures, including parsing 
    crystal files, determining symmetries, and accessing atomic information.
  doc_url: 'https://crystals.readthedocs.io/'
  dev_url: 'https://github.com/LaurentRDC/crystals'

extra:
  recipe-maintainers: 
    - LaurentRDC
